blank_issues_enabled: true
contact_links:
  - name: Contact Us
    url: https://scratchaddons.com/docs/faq/#what-can-i-do-if-i-find-a-problem
    about: Want to say something about Scratch Addons? Learn more about how to reach/tell/contact us!
